Сделал разметку страниц барбершопа.
petitechatte/sanya-learning pull request #1
Opened 2021-03-23 07:47 UTC by Nomad48JMS

Сделал разметку.  4 страницы. Прогнал код на валидацию ошибки исправил.
В принципе все работает но есть вопросы по самой разметке. По названию файлов и по ссылкам.

2021-03-23 07:54 UTC, Nomad48JMS reviewed
Так в целом то все понятно. Но надо чтобы ты посмотрела что я сделал.

2021-03-23 07:54 UTC, Nomad48JMS commented on README.md
> +* Студент: [Nomad48JMS].
Мой никнейм.

2021-03-23 07:54 UTC, Nomad48JMS commented on index.html
> +           <li><a href="catalog.html">Магазин</a></li>
Есть вопрос с названием файлов страниц. Я сделал произвольно свои названия но в разметке испольовал их названия. Может стоит поменять?

2021-03-23 07:54 UTC, Nomad48JMS commented on index.html
> +        <span class="button gallery-button gallery-button-back">Назад</span>
немного не понял с названиями классов здесь есть вопросы

2021-03-23 07:54 UTC, Nomad48JMS commented on shop.html
> +        <span class="modal-close">x</span>
не понял как лучше размечать кнопки есть вопросы

2021-03-23 07:57 UTC, Nomad48JMS commented
+ я в этот же репозиторий скинул макет

2021-04-10 16:07 UTC, petitechatte requested changes
Пока нашла самые очевидные ошибки. Когда пофиксишь, проверю подробнее.

2021-04-10 16:07 UTC, petitechatte commented on index.html
>    <body>
Грубая ошибка: body болтается отдельно от всего содержимого.

2021-04-10 16:07 UTC, petitechatte commented on index.html
> +        <span class="button gallery-button gallery-button-back">Назад</span>
1.  В названиях файлов не стоит использовать заглавные буквы.
2.  Названия файлов желательно делать осмысленными. Как и все в коде.
3. На главной странице не нужно делать ссылку на себя же.  То есть логотип либо вообще не оборачивать в ссылку (т.к. на других страницах он выглядит и располагается по-другому), либо не прописывать адрес в src.

2021-04-10 16:07 UTC, petitechatte commented on css/BARBER PRICE export css.txt
> +﻿footer как на item
Это все лишнее. Надо удалить.

2021-04-10 16:07 UTC, petitechatte commented on css/BARBER SHOP export css.txt
> +﻿footer как на item
Это тоже под снос.

2021-04-10 16:07 UTC, petitechatte commented on img/Layer 12 copy 13.svg
> +<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="78" height="43" viewBox="0 0 78 43">
Неправильный способ вставки svg: растровый файл внутри тэга svg.

2021-04-10 16:10 UTC, petitechatte commented on index.html
> +           <li><a href="catalog.html">Магазин</a></li>
Нет, вполне нормальные названия.

2021-04-10 16:12 UTC, petitechatte commented on shop.html
> +        <span class="modal-close">x</span>
Кнопка должна быть button. Но можешь пока оставить так, потом, когда будешь учить JS, переделаешь.

2021-04-10 18:04 UTC, petitechatte requested changes
Проверила верстку. Получите ваши правки))

2021-04-10 18:04 UTC, petitechatte commented on img/cross.svg
> +<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="19" height="19" viewBox="0 0 19 19">
Это растровая графика внутри svg. Нужен другой формат.

2021-04-10 18:04 UTC, petitechatte commented on img/user.svg
> +<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="13" height="13" viewBox="0 0 13 13">
Это растровая графика внутри svg. Нужен другой формат.

2021-04-10 18:04 UTC, petitechatte commented on img/сross-map-popup.svg
> +<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="19" height="19" viewBox="0 0 19 19">
Это растровая графика внутри svg. Нужен другой формат.

2021-04-10 18:04 UTC, petitechatte commented on index.html
> +      <section classh="gallery">
Опечатка в атрибуте тэга!

2021-04-10 18:04 UTC, petitechatte commented on img/form-radio-clear.svg
> +<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="20" height="20" viewBox="0 0 20 20">
Это растровая графика внутри svg. Нужен другой формат.

2021-04-10 18:04 UTC, petitechatte commented on img/index-logo.svg
> +<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="371" height="155" viewBox="0 0 371 155">
Это растровая графика внутри svg. Нужен другой формат.

2021-04-10 18:04 UTC, petitechatte commented on img/instagram.svg
> +<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="20" height="20" viewBox="0 0 20 20">
Это растровая графика внутри svg. Нужен другой формат.

2021-04-10 18:04 UTC, petitechatte commented on img/logo.svg
> +<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="111" height="24" viewBox="0 0 111 24">
Это растровая графика внутри svg. Нужен другой формат.

2021-04-10 18:04 UTC, petitechatte commented on img/vk.svg
> +<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="27" height="15" viewBox="0 0 27 15">
Это растровая графика внутри svg. Нужен другой формат.

2021-04-10 18:04 UTC, petitechatte commented on index.html
> +         <a class="main-header-logo" href="index.html" aria-label="Логотип ссылка на главную страницу.">
Рекурсивная ссылка на себя считается дурным тоном.

2021-04-10 18:04 UTC, petitechatte commented on index.html
> +           <li class="login-link"><a href="index.html" aria-label="Вход в учетную запись.">Вход</a></li>
А здесь почему опять ссылка на себя?

2021-04-10 18:04 UTC, petitechatte commented on index.html
> +          <h3>Быстро</h3>
Не забывай про отступы для вложенных тегов.

2021-04-10 18:04 UTC, petitechatte commented on index.html
> +          <h3>Быстро</h3>
И это скорее всего не заголовок, а просто слоган. Вот тут как раз уместен тэг b.

2021-04-10 18:04 UTC, petitechatte commented on index.html
> +        <h2>Контактрая информация</h2>
Опечатка!

2021-04-10 18:04 UTC, petitechatte commented on index.html
> +        <form action="hhtp://echo.htmlacademy.ru" method="get" class="appoimtment-form" aria-label="Форма записи на прием к мастеру.">
Эта форма с личными данными, ее нельзя отправлять методом get.

2021-04-10 18:04 UTC, petitechatte commented on index.html
> +           <input type="text" name="name" id="form-name" value="" placeholder="Борода" aria-label="Введите ваit имя.">
Опечатка в aria-label!

2021-04-10 18:04 UTC, petitechatte commented on index.html
> +           <label for="form-phone">Время:</label>
Неправильная подпись к полю!

2021-04-10 18:04 UTC, petitechatte commented on index.html
> +           <input type="submit" name="form-button" value="Отправить" aria-label="Кнопка отправки формы.">
Зачем имя для кнопки отправки?

2021-04-10 18:04 UTC, petitechatte commented on index.html
> +          <fieldset>
В одном филдсете смысла никакого нет. Это тэг для группировки полей внутри большой формы. Например, все поля с контактными данными, все поля для характеристики заказа и т.д.

2021-04-10 18:04 UTC, petitechatte commented on index.html
> +      </main>
Опять непорядок с отступами вложенных тегов.

2021-04-10 18:04 UTC, petitechatte commented on index.html
> +        <p class="footer-contact"></p>
А где контакты?

2021-04-10 18:04 UTC, petitechatte commented on index.html
> +        <form action="hhtp://    echo.htmlacademy.ru" method="post" class="modal-login-form" aria-label="Форма входа в учетную запись.">
Непонятные пробелы в адресе.

2021-04-10 18:04 UTC, petitechatte commented on index.html
> +        <form action="hhtp://    echo.htmlacademy.ru" method="post" class="modal-login-form" aria-label="Форма входа в учетную запись.">
В этой форме дизайнер нарисовал лейблы на месте плейсхолдеров. Очень плохое и недоступное решение, которое ты как верстальщик должен исправить.

2021-04-10 18:04 UTC, petitechatte commented on index.html
> +          <input type="radio" name="" id="modal-login-radio" aria-label="Стоит ли запомнить ваши данные при отправке.">
Здесь нужен чекбокс. Радиобаттон ты не можешь отжать обратно, и он предназначен для выбора одного из нескольких вариантов.

2021-04-10 18:04 UTC, petitechatte commented on index.html
> +          <label for="modal-login-radio">ЗАПОМНИТЕ МЕНЯ</label>
Здесь лучше не использовать капслок, как и во всем остальном тексте.

2021-04-10 18:04 UTC, petitechatte commented on index.html
> +          <input type="submit" value="ВОЙТИ" aria-label="Кнопка входа в учетную запись.">
Подумай, как ты будешь стилизовать этот инпут.

2021-04-10 18:04 UTC, petitechatte commented on index.html
> +        <img src="img/Map-popup.png" width="782px" height="577px" alt="Карта на которой показано как к нам проехать.">
Не используй прописные буквы для названия файлов.
В описании изображения не хватает двух запятых.

2021-04-10 18:04 UTC, petitechatte commented on item.html
> +        <img src="img/logo.svg" width="111" height="24" alt="Логотип барбершопа Бородинский">
Не хватает отступа для вложенного тега.

2021-04-10 18:04 UTC, petitechatte commented on item.html
> +          <li class="login-link"><a href="index.html" aria-label="Вход в учетную запись.">Вход</a></li>
Почему ссылка на главную?

2021-04-10 18:04 UTC, petitechatte commented on item.html
> +        <li><a href="item.html">Магазин</a></li>
Здесь должна быть ссылка на магазин! Не вводи пользователей в заблуждение.

2021-04-10 18:04 UTC, petitechatte commented on item.html
> +        <p class="footer-contact"></p>
И снова: где контакты?

2021-04-10 18:04 UTC, petitechatte commented on map.html
> +  <img src="img/map-borodinsky.png" width="766" height="560" alt="" aria-label="">
Не заполнены атрибуты alt и aria-label.

2021-04-10 18:04 UTC, petitechatte commented on map.html
> +</html>
Отступы тут тоже стоит поправить.

2021-04-10 18:04 UTC, petitechatte commented on price.html
> +          чувствовать себя комфортно и свободно!</p>
Так делать нельзя! В тексте не должно быть ручных переносов строки!

2021-04-10 18:04 UTC, petitechatte commented on price.html
> +          <li class="site-navigation-current"aria-label="Ссылка на текущую страницу с ипрайс листом." ><a href="#">Прайс-лист</a></li>
Здесь нужно убрать атрибут href, чтобы эта неактивная ссылка не подсвечивалась и не получала фокус.

2021-04-10 18:04 UTC, petitechatte commented on shop.html
> +          <li class="login-link"><a href="index.html" aria-label="Вход в учетную запись.">Вход</a></li>
Ссылка опять ведет не туда.

2021-04-10 18:04 UTC, petitechatte commented on shop.html
> +        <li><a href="item.html">Магазин</a></li>
Неправильная ссылка.

2021-04-10 18:04 UTC, petitechatte commented on shop.html
> +             <a href="catalog-item.html">
У тебя этот файл называется по-другому.

2021-04-10 18:04 UTC, petitechatte commented on shop.html
> +              <a href="catalog-item.html">
В остальных товарах лучше поставить ссылку-заглушку.

2021-04-13 13:13 UTC, closed without merging

2021-04-13 18:28 UTC, Nomad48JMS reviewed
Исправил замечания

2021-04-13 18:28 UTC, Nomad48JMS commented on index.html
> +         <a class="main-header-logo" href="index.html" aria-label="Логотип ссылка на главную страницу.">
Убрал ссылку на логотипе.

2021-04-13 18:28 UTC, Nomad48JMS commented on index.html
> +           <li class="login-link"><a href="index.html" aria-label="Вход в учетную запись.">Вход</a></li>
Сделал ссылку на login.html

2021-04-13 18:28 UTC, Nomad48JMS commented on index.html
> +          <h3>Быстро</h3>
Отступы я подправил
Но <h1> сделали челики из академии и они как раз тоже считают, что это заголовок.

2021-04-13 18:28 UTC, Nomad48JMS commented on index.html
> +      <section classh="gallery">
Исправил опечатку

2021-04-13 18:28 UTC, Nomad48JMS commented on index.html
> +        <h2>Контактрая информация</h2>
Исправил опечатку.

2021-04-13 18:28 UTC, Nomad48JMS commented on index.html
> +        <form action="hhtp://echo.htmlacademy.ru" method="get" class="appoimtment-form" aria-label="Форма записи на прием к мастеру.">
Исправил на method="post"

2021-04-13 18:28 UTC, Nomad48JMS commented on index.html
> +          <fieldset>
Убрал филдсет

2021-04-13 18:28 UTC, Nomad48JMS commented on index.html
> +           <input type="text" name="name" id="form-name" value="" placeholder="Борода" aria-label="Введите ваit имя.">
Исправил опечатку.

2021-04-13 18:28 UTC, Nomad48JMS commented on index.html
> +           <label for="form-phone">Время:</label>
Исправил опечатку.

2021-04-13 18:28 UTC, Nomad48JMS commented on index.html
> +           <input type="submit" name="form-button" value="Отправить" aria-label="Кнопка отправки формы.">
Убрал имя кнопки отправки формы.

2021-04-13 18:28 UTC, Nomad48JMS commented on index.html
> +      </main>
Исправил отступы у тега main.

2021-04-13 18:28 UTC, Nomad48JMS commented on index.html
> +        <p class="footer-contact"></p>
Добавил. Пропустил сорян.

2021-04-13 18:28 UTC, Nomad48JMS commented on index.html
> +        <form action="hhtp://    echo.htmlacademy.ru" method="post" class="modal-login-form" aria-label="Форма входа в учетную запись.">
Пробелы в адресе исправил.

2021-04-13 18:28 UTC, Nomad48JMS commented on index.html
> +        <form action="hhtp://    echo.htmlacademy.ru" method="post" class="modal-login-form" aria-label="Форма входа в учетную запись.">
я aria-label сделал к полям. А еще потом когда я дойду до момента в курсе где про это говорят- то исправлю.

2021-04-13 18:28 UTC, Nomad48JMS commented on index.html
> +          <input type="radio" name="" id="modal-login-radio" aria-label="Стоит ли запомнить ваши данные при отправке.">
Исправил на чекбокс

2021-04-13 18:28 UTC, Nomad48JMS commented on index.html
> +          <label for="modal-login-radio">ЗАПОМНИТЕ МЕНЯ</label>
Я исправил.

2021-04-13 18:28 UTC, Nomad48JMS commented on index.html
> +          <input type="submit" value="ВОЙТИ" aria-label="Кнопка входа в учетную запись.">
Поменял на баттон с классом

2021-04-13 18:28 UTC, Nomad48JMS commented on index.html
> +        <img src="img/Map-popup.png" width="782px" height="577px" alt="Карта на которой показано как к нам проехать.">
Исправил названия. И исправил запятые в описании.

2021-04-13 18:28 UTC, Nomad48JMS commented on item.html
> +          <li class="login-link"><a href="index.html" aria-label="Вход в учетную запись.">Вход</a></li>
исправил

2021-04-13 18:28 UTC, Nomad48JMS commented on item.html
> +        <li><a href="item.html">Магазин</a></li>
Это я уже исправил.

2021-04-13 18:28 UTC, Nomad48JMS commented on item.html
> +        <p class="footer-contact"></p>
добавил

2021-04-13 18:28 UTC, Nomad48JMS commented on map.html
> +  <img src="img/map-borodinsky.png" width="766" height="560" alt="" aria-label="">
Исправил

2021-04-13 18:28 UTC, Nomad48JMS commented on map.html
> +</html>
Исправил

2021-04-13 18:28 UTC, Nomad48JMS commented on price.html
> +          <li class="site-navigation-current"aria-label="Ссылка на текущую страницу с ипрайс листом." ><a href="#">Прайс-лист</a></li>
Исправил

2021-04-13 18:28 UTC, Nomad48JMS commented on price.html
> +          чувствовать себя комфортно и свободно!</p>
Так сказали делать чуваки с академии. И сказали что именно в адресах так и нужно делать использовать тег <br> там он легален и уместен.

2021-04-13 18:28 UTC, Nomad48JMS commented on shop.html
> +          <li class="login-link"><a href="index.html" aria-label="Вход в учетную запись.">Вход</a></li>
исправил

2021-04-13 18:28 UTC, Nomad48JMS commented on shop.html
> +        <li><a href="item.html">Магазин</a></li>
исправил

2021-04-13 18:28 UTC, Nomad48JMS commented on shop.html
> +             <a href="catalog-item.html">
Исправил

2021-04-13 18:28 UTC, Nomad48JMS commented on shop.html
> +              <a href="catalog-item.html">
Исправил